name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CMAKE_BUILD_PARALLEL_LEVEL: 4

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.f90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"

jobs:

  unix:
    strategy:
      matrix:
        shared: [true, false]
        os: ['ubuntu-latest']

    runs-on: ${{ matrix.os }}
    env:
      FC: gfortran-13

    steps:
    - uses: actions/checkout@v4

    - name: Config library
      run: cmake -B build -DMPI1:BOOL=on --install-prefix=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    - name: build library
      run: cmake --build build
    - name: install library
      run: cmake --install build

    - name: Config example
      run: cmake -S example -B example/build -DCMAKE_PREFIX_PATH=${{ runner.temp }}
    - name: build example
      run: cmake --build example/build
    - name: test example
      run: ctest --test-dir example/build -V
